// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendDebugLog(arg1:string):Promise<Record<string, any>>;

export function BackupDatabase(arg1:Record<string, any>):Promise<Record<string, any>>;

export function ChangeDatabaseStorageMode(arg1:string):Promise<Record<string, any>>;

export function CheckForUpdate(arg1:Record<string, any>):Promise<Record<string, any>>;

export function CleanupEventRetention():Promise<Record<string, any>>;

export function CompleteDataImport(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DBRequest(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DownloadAndInstallUpdate(arg1:Record<string, any>):Promise<Record<string, any>>;

export function ExportDiagnosticsBundle():Promise<Record<string, any>>;

export function GetAppVersion():Promise<string>;

export function GetArchiveInfo():Promise<Record<string, any>>;

export function GetDatabaseStorageInfo():Promise<Record<string, any>>;

export function GetDbInfo():Promise<Record<string, any>>;

export function GetEncryptionStatus():Promise<Record<string, any>>;

export function GetHostname():Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetOdbcDsns():Promise<Record<string, any>>;

export function GetOdbcTables(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetPasscodeStatus():Promise<Record<string, any>>;

export function GetStartupSetting():Promise<Record<string, any>>;

export function GetTerminalApiToken():Promise<Record<string, any>>;

export function GetTerminalRole():Promise<Record<string, any>>;

export function GetUpdateDistInfo():Promise<Record<string, any>>;

export function GetWatchDirectory():Promise<Record<string, any>>;

export function ImportUpdateFiles():Promise<Record<string, any>>;

export function IsDevMode():Promise<boolean>;

export function OpenDebugLog():Promise<Record<string, any>>;

export function ParentHttpRequest(arg1:Record<string, any>):Promise<Record<string, any>>;

export function PreviewOdbcQuery(arg1:Record<string, any>):Promise<Record<string, any>>;

export function ReadCsvHeaders(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RelaunchApp():Promise<Record<string, any>>;

export function ReloadScheduleFeedTriggers():Promise<Record<string, any>>;

export function ResetDatabase(arg1:string):Promise<Record<string, any>>;

export function RestoreDatabase(arg1:Record<string, any>):Promise<Record<string, any>>;

export function RollbackUpdateDist():Promise<Record<string, any>>;

export function RunOdbcSync(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SelectFolder():Promise<Record<string, any>>;

export function SetAdminPasscode(arg1:string):Promise<Record<string, any>>;

export function SetAlwaysOnTop(arg1:boolean):Promise<Record<string, any>>;

export function SetPowerSave(arg1:boolean):Promise<Record<string, any>>;

export function SetStartupSetting(arg1:Record<string, any>):Promise<Record<string, any>>;

export function SetTerminalApiToken(arg1:string):Promise<Record<string, any>>;

export function SetTerminalRole(arg1:string):Promise<Record<string, any>>;

export function TestOdbcConnection(arg1:Record<string, any>):Promise<Record<string, any>>;

export function ToggleFullscreen():Promise<Record<string, any>>;

export function TriggerManualImport():Promise<Record<string, any>>;

export function TriggerScheduleFeedImport(arg1:string):Promise<Record<string, any>>;

export function UpdateWatchDirectory(arg1:string):Promise<Record<string, any>>;

export function VerifyAdminPasscode(arg1:string):Promise<Record<string, any>>;

export function WebrtcRequest(arg1:Record<string, any>):Promise<Record<string, any>>;
