// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendDebugLog(arg1) {
  return window['go']['main']['App']['AppendDebugLog'](arg1);
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function ChangeDatabaseStorageMode(arg1) {
  return window['go']['main']['App']['ChangeDatabaseStorageMode'](arg1);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function CleanupEventRetention() {
  return window['go']['main']['App']['CleanupEventRetention']();
}

export function CompleteDataImport(arg1) {
  return window['go']['main']['App']['CompleteDataImport'](arg1);
}

export function DBRequest(arg1) {
  return window['go']['main']['App']['DBRequest'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportDiagnosticsBundle() {
  return window['go']['main']['App']['ExportDiagnosticsBundle']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetArchiveInfo() {
  return window['go']['main']['App']['GetArchiveInfo']();
}

export function GetDatabaseStorageInfo() {
  return window['go']['main']['App']['GetDatabaseStorageInfo']();
}

export function GetDbInfo() {
  return window['go']['main']['App']['GetDbInfo']();
}

export function GetEncryptionStatus() {
  return window['go']['main']['App']['GetEncryptionStatus']();
}

export function GetHostname() {
  return window['go']['main']['App']['GetHostname']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetOdbcDsns() {
  return window['go']['main']['App']['GetOdbcDsns']();
}

export function GetOdbcTables(arg1) {
  return window['go']['main']['App']['GetOdbcTables'](arg1);
}

export function GetPasscodeStatus() {
  return window['go']['main']['App']['GetPasscodeStatus']();
}

export function GetStartupSetting() {
  return window['go']['main']['App']['GetStartupSetting']();
}

export function GetTerminalApiToken() {
  return window['go']['main']['App']['GetTerminalApiToken']();
}

export function GetTerminalRole() {
  return window['go']['main']['App']['GetTerminalRole']();
}

export function GetUpdateDistInfo() {
  return window['go']['main']['App']['GetUpdateDistInfo']();
}

export function GetWatchDirectory() {
  return window['go']['main']['App']['GetWatchDirectory']();
}

export function ImportUpdateFiles() {
  return window['go']['main']['App']['ImportUpdateFiles']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function OpenDebugLog() {
  return window['go']['main']['App']['OpenDebugLog']();
}

export function ParentHttpRequest(arg1) {
  return window['go']['main']['App']['ParentHttpRequest'](arg1);
}

export function PreviewOdbcQuery(arg1) {
  return window['go']['main']['App']['PreviewOdbcQuery'](arg1);
}

export function ReadCsvHeaders(arg1, arg2) {
  return window['go']['main']['App']['ReadCsvHeaders'](arg1, arg2);
}

export function RelaunchApp() {
  return window['go']['main']['App']['RelaunchApp']();
}

export function ReloadScheduleFeedTriggers() {
  return window['go']['main']['App']['ReloadScheduleFeedTriggers']();
}

export function ResetDatabase(arg1) {
  return window['go']['main']['App']['ResetDatabase'](arg1);
}

export function RestoreDatabase(arg1) {
  return window['go']['main']['App']['RestoreDatabase'](arg1);
}

export function RollbackUpdateDist() {
  return window['go']['main']['App']['RollbackUpdateDist']();
}

export function RunOdbcSync(arg1) {
  return window['go']['main']['App']['RunOdbcSync'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetAdminPasscode(arg1) {
  return window['go']['main']['App']['SetAdminPasscode'](arg1);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetPowerSave(arg1) {
  return window['go']['main']['App']['SetPowerSave'](arg1);
}

export function SetStartupSetting(arg1) {
  return window['go']['main']['App']['SetStartupSetting'](arg1);
}

export function SetTerminalApiToken(arg1) {
  return window['go']['main']['App']['SetTerminalApiToken'](arg1);
}

export function SetTerminalRole(arg1) {
  return window['go']['main']['App']['SetTerminalRole'](arg1);
}

export function TestOdbcConnection(arg1) {
  return window['go']['main']['App']['TestOdbcConnection'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function TriggerManualImport() {
  return window['go']['main']['App']['TriggerManualImport']();
}

export function TriggerScheduleFeedImport(arg1) {
  return window['go']['main']['App']['TriggerScheduleFeedImport'](arg1);
}

export function UpdateWatchDirectory(arg1) {
  return window['go']['main']['App']['UpdateWatchDirectory'](arg1);
}

export function VerifyAdminPasscode(arg1) {
  return window['go']['main']['App']['VerifyAdminPasscode'](arg1);
}

export function WebrtcRequest(arg1) {
  return window['go']['main']['App']['WebrtcRequest'](arg1);
}
